source = $HOME/.config/hypr/themes/mocha.conf

background = rgba($crustAlphaFF)
base = rgba($baseAlphaFF)
text = rgba($textAlphaFF)
alternate_base = rgba($mantleAlphaFF)
bright_text = rgba($rosewaterAlphaFF)
accent = rgba($blueAlphaFF)
accent_secondary = rgba($blueAlphaFF)
