# Enable Colors
set -g default-terminal 'tmux-256color'
set -as terminal-features ",xterm-ghostty:RGB,hyperlinks,usstyle"
set -g allow-passthrough on
set -s set-clipboard on

# Base index
set -g base-index 1

# Renumber all windows when a window is closed
set -g renumber-windows on

# Open new windows in current directory path
bind c new-window -c "#{pane_current_path}"

# Split Windows
unbind %
bind l split-window -h -c "#{pane_current_path}"
unbind '"'
bind j split-window -v -c "#{pane_current_path}"
bind k split-window -vb -c "#{pane_current_path}"
bind h split-window -hb -c "#{pane_current_path}"

# Reload Config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "󰑓 Config reloaded"

# Resize Panes
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind -r H resize-pane -L 5
bind -r z resize-pane -Z

# Kill pane without confirmation
bind x kill-pane

# Kill window without confirmation
bind u kill-window

# Enable Mouse
set -g mouse on

# Scrollback
set -g history-limit 50000

# VIM motions
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

# Enable Mouse Dragging
unbind -T copy-mode-vi MouseDragEnd1Pane

# Status Line Position
set-option -g status-position top

##### Plugins #####
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

# Catppuccin config
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_window_flags_icon_format "##{?window_zoomed_flag,#{E:@catppuccin_window_flags_icon_zoom} ,}"

run '~/.config/tmux/plugins/tmux/catppuccin.tmux' 

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right ""

##### Neovim CheckHealth Recommendations #####
set-option -sg escape-time 10
set-option -g focus-events on

##### TPM Init #####
run '~/.tmux/plugins/tpm/tpm'
